"""
Pull Request Agent — Creates and manages pull requests.

When AI is enabled, Claude reads the actual diff and code to write an
intelligent PR summary — understanding what the code does, not just listing
files that changed. Like asking Cursor to "create a PR for this branch".

When AI is disabled, generates a structured PR from diff metadata.
"""

import subprocess
from pathlib import Path

from .base import BaseAgent
from orchestrator import HandoffEnvelope, WorkflowConfig

PR_SUMMARY_SYSTEM = """\
You are a senior data engineer writing a pull request description.
You have access to tools to read files, run git commands, and examine code.

Rules:
- Use git diff and read the changed files to understand WHAT the code does.
- Write a clear, concise PR description that explains the purpose and approach.
- Include a summary section, a description of key changes, and test results.
- Use markdown formatting.
- Be specific about data transformations, quality checks, and business logic.
- Do NOT just list file names — explain what the code actually does.
- Return ONLY the PR body text (markdown). No code blocks wrapping it.
"""


class PullRequestAgent(BaseAgent):

    def execute(self, envelope: HandoffEnvelope, config: WorkflowConfig) -> HandoffEnvelope:
        repo = Path(config.repo_path)
        branch = envelope.branch
        base = config.base_branch

        self.logger.info(f"Creating PR: {branch} → {base}")

        try:
            diff_summary = self._get_diff_summary(repo, base, branch)
            commit_log = self._get_commit_log(repo, base, branch)
            test_results = self._format_test_results(envelope.metadata)

            title = self._generate_title(envelope.ticket_ref, diff_summary)

            if self.ai_enabled:
                self.logger.info("Using AI to generate PR description")
                body = self._generate_body_with_ai(
                    envelope.ticket_ref, base, branch, test_results, envelope.metadata,
                )
            else:
                body = self._generate_body_template(
                    envelope.ticket_ref, diff_summary, commit_log,
                    test_results, envelope.metadata,
                )

            pr_url = self._create_pr(repo, branch, base, title, body)

            self.logger.info(f"PR created: {pr_url}")
            return self._success(
                envelope,
                pr_url=pr_url,
                pr_title=title,
                ai_generated=self.ai_enabled,
            )

        except Exception as e:
            return self._failure(envelope, f"PR creation failed: {e}")

    def _generate_body_with_ai(
        self, ticket: str, base: str, branch: str, test_results: str, metadata: dict,
    ) -> str:
        """Let AI read the diff and code to write an intelligent PR summary."""
        coverage = metadata.get("coverage", "N/A")

        user_prompt = f"""\
Write a pull request description for merging `{branch}` into `{base}`.
Ticket: {ticket}

First, run these commands to understand the changes:
1. `git diff --stat {base}...{branch}` to see what files changed
2. `git diff {base}...{branch}` to see the actual code diff
3. Read any new files that were added

Then write the PR body. Include:
- A summary of what this pipeline does (read the actual code to understand it)
- Key technical decisions (data transformations, quality checks)
- Test results: {test_results}
- Coverage: {coverage}

End with a checklist.
"""
        return self.ai.run_agent(PR_SUMMARY_SYSTEM, user_prompt)

    def _generate_body_template(
        self, ticket: str, diff_summary: dict, commit_log: str,
        test_results: str, metadata: dict,
    ) -> str:
        pipeline_name = metadata.get("pipeline_name", "N/A")
        files_list = "\n".join(f"- `{f}`" for f in diff_summary["files_changed"])

        return f"""## Summary

Automated PR for **{ticket}** — Pipeline: `{pipeline_name}`

This PR was generated by the Multi-Agent Data Engineering system.

## Changes

{files_list}

## Commits

```
{commit_log}
```

## Test Results

{test_results}

## Checklist

- [x] Pipeline code generated from spec
- [x] Unit tests generated and passing
- [x] Linting checks passed
- [ ] Manual review completed
- [ ] Data quality validated in staging

---
*Generated by PR Agent v1.0 | Workflow: multi-agent-orchestrator*
"""

    def _get_diff_summary(self, repo: Path, base: str, branch: str) -> dict:
        result = subprocess.run(
            ["git", "diff", "--stat", f"{base}...{branch}"],
            cwd=repo, capture_output=True, text=True, check=True,
        )
        stat_output = result.stdout.strip()

        result = subprocess.run(
            ["git", "diff", "--name-only", f"{base}...{branch}"],
            cwd=repo, capture_output=True, text=True, check=True,
        )
        files = [f for f in result.stdout.strip().splitlines() if f]

        return {
            "stat": stat_output,
            "files_changed": files,
            "file_count": len(files),
        }

    def _get_commit_log(self, repo: Path, base: str, branch: str) -> str:
        result = subprocess.run(
            ["git", "log", "--oneline", f"{base}...{branch}"],
            cwd=repo, capture_output=True, text=True, check=True,
        )
        return result.stdout.strip()

    def _format_test_results(self, metadata: dict) -> str:
        lines = []
        if metadata.get("tests_passed"):
            lines.append("- Unit Tests: PASSED")
        else:
            lines.append("- Unit Tests: FAILED")

        if metadata.get("lint_passed"):
            lines.append("- Linting: PASSED")
        else:
            lines.append("- Linting: FAILED")

        coverage = metadata.get("coverage", "N/A")
        lines.append(f"- Coverage: {coverage}")

        return "\n".join(lines)

    def _generate_title(self, ticket: str, diff_summary: dict) -> str:
        pipeline_files = [
            f for f in diff_summary["files_changed"]
            if f.startswith("pipelines/") and f.endswith(".py")
        ]
        if pipeline_files:
            name = Path(pipeline_files[0]).stem
            return f"feat({ticket}): add {name} pipeline"
        return f"feat({ticket}): pipeline changes"

    def _create_pr(self, repo: Path, branch: str, base: str, title: str, body: str) -> str:
        try:
            subprocess.run(
                ["git", "push", "--force", "-u", "origin", branch],
                cwd=repo, capture_output=True, text=True, check=True,
            )
            result = subprocess.run(
                [
                    "gh", "pr", "create",
                    "--base", base,
                    "--head", branch,
                    "--title", title,
                    "--body", body,
                ],
                cwd=repo, capture_output=True, text=True, check=True,
            )
            return result.stdout.strip()
        except FileNotFoundError:
            self.logger.info("gh CLI not installed — falling back to local simulation")
            return self._simulate_pr(repo, branch, base, title, body)
        except subprocess.CalledProcessError as e:
            stderr = e.stderr.strip() if e.stderr else str(e)
            self.logger.warning(f"gh pr create failed ({stderr}) — falling back to local simulation")
            return self._simulate_pr(repo, branch, base, title, body)

    def _simulate_pr(self, repo: Path, branch: str, base: str, title: str, body: str) -> str:
        self.logger.info("gh CLI not found — simulating PR creation locally")
        pr_dir = repo / ".pull_requests"
        pr_dir.mkdir(exist_ok=True)

        pr_file = pr_dir / f"PR-{branch.replace('/', '-')}.md"
        content = f"# {title}\n\n**Base:** {base} <- **Head:** {branch}\n\n{body}"
        pr_file.write_text(content)

        url = f"https://github.com/org/repo/pull/1 (simulated — see {pr_file.name})"
        self.logger.info(f"Simulated PR written to: {pr_file}")
        return url
